[package]
name = "pobsdrs-server"
version = "0.1.0"
edition = "2021"

[dependencies]
pobsdlib = { path = "../pobsdlib" }
askama = "0.11"
axum = "0.4"
tokio = { version = "1.0", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
reqwest = "0.11"
rss = "2"
chrono = "0.4"