//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "runtime_game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub runtime_id: i32,
    pub game_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::runtime::Entity",
        from = "Column::RuntimeId",
        to = "super::runtime::Column::Id"
    )]
    Runtime,
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id"
    )]
    Game,
}

impl ActiveModelBehavior for ActiveModel {}
