//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        super::tag_game::Relation::Game.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::tag_game::Relation::Tag.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
