[package]
name = "pobsdrs"
version = "0.1.0"
edition = "2021"

[dependencies]
pobsdlib = { path = "../pobsdlib" }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

